# Generated by Django 3.0.8 on 2022-01-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('char_thumbnail_path', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('format', models.CharField(max_length=1000, null=True)),
                ('issueNumber', models.IntegerField()),
                ('comic_thumbnail_path', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('char_thumbnail_path', models.CharField(max_length=4000)),
                ('character', models.ManyToManyField(to='dashboard.Characters')),
                ('comic', models.ManyToManyField(to='dashboard.Comic')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('char_thumbnail_path', models.CharField(max_length=4000)),
                ('character', models.ManyToManyField(to='dashboard.Characters')),
                ('comic', models.ManyToManyField(to='dashboard.Comic')),
                ('event', models.ManyToManyField(to='dashboard.Events')),
            ],
        ),
        migrations.AddField(
            model_name='characters',
            name='comic',
            field=models.ManyToManyField(to='dashboard.Comic'),
        ),
    ]
